### PR TITLE
Changes from gocardless-pro-java-template

### PR DESCRIPTION
**Pull request by gocardless-robot-restricted**

### CODE REVIEW

**Comment by paprikati** [comment]
@jasonlafferty was there another enum you wanted to fix before we merge this?

**Comment by ankithads** [comment]
@gocardless/connect @gocardless/mixp can I please get the approval for this?

**Comment by paprikati** [comment]
Want to get confirmation from MIXP that there's not another enum we want to include first

**Comment by jasonlafferty** [comment]
@paprikati there is no enum we want to change atm, we intend to change you saw with a larger change to payment-service.

**Pull request merged**
